#!/usr/bin/env bash

toplevel=$(git rev-parse --show-toplevel) || exit

color=auto args=()
while (( $# > 0 )) ; do
  case $1 in
    (--color|--color=always) color=always ;;
    (--no-color|--color=never) color=never ;;
    (--color=auto) color=auto ;;
    (--cached|--staged) args+=( "$1" ) ;;
    (--|''|[!-]*) break ;;
    (*) printf >&2 '%s: Unknown option: %s\n' "$0" "$1" ; exit 1 ;;
  esac
  shift
done
args+=( "$@" )

if [[ $color = never ]] ; then
  :
elif [[ $color = always || -t 1 || $GIT_PAGER_IN_USE = true ]] ; then
  color_header=$(git config --get-color color.diff.meta bold)
  color_hunk_header=$(git config --get-color color.diff.frag cyan)
  color_new=$(git config --get-color color.diff.new green)
  color_old=$(git config --get-color color.diff.old red)
  sgr0=$(tput sgr0)
fi
unset -v GIT_PAGER_IN_USE

revs=()
while IFS= read -r rev ; do
  revs+=("$rev")
done < <(git rev-parse --revs-only "$@")

git diff "${args[@]}" | while IFS= read -r line ; do
  case $line in
    (diff\ --git\ *)
      exec 3<&- 4<&-
      printf '%s%s%s\n' "$color_header" "$line" "$sgr0"
      while IFS= read -r line ; do
        printf '%s%s%s\n' "$color_header" "$line" "$sgr0"
        if [[ $line = ---* ]] ; then
          old=1
          if [[ $line = ---\ /dev/null ]] ; then
            exec 3< /dev/null
          elif [[ $line = ---* ]] ; then
            exec 3< <(git -C "$toplevel" blame "${revs[0]-HEAD}" -- "${line:6}")
          fi
        elif [[ $line = +++* ]] ; then
          new=1
          if [[ $line = +++\ /dev/null ]] ; then
            exec 4< /dev/null
          elif [[ $line = +++* ]] ; then
            exec 4< <(git -C "$toplevel" blame ${revs[1]+"${revs[1]}"} -- "${line:6}")
          fi
          break
        fi
      done
    ;;
    (@@*)
      [[ $line =~ @@\ ([^@]+)\ @@(.*) ]] || continue
      ranges=${BASH_REMATCH[1]}
      context=${BASH_REMATCH[2]}
      printf '%s@@ %s @@%s%s\n' "$color_hunk_header" "$ranges" "$sgr0" "$context"
      [[ $ranges =~ -([[:digit:]]+),[[:digit:]]+' +'([[:digit:]]+), ]] || continue
      oldfrom=${BASH_REMATCH[1]}
      newfrom=${BASH_REMATCH[2]}

      for (( ; old < oldfrom; old++ )) ; do read -ru 3 _ || break ; done
      for (( ; new < newfrom; new++ )) ; do read -ru 4 _ || break ; done
    ;;
    (' '*)
      read -ru 3 _
      ((old++))
      read -ru 4 hash _
      ((new++))
      printf '%s %s\n' "${hash::7}" "$line"
    ;;
    (-*)
      read -ru 3 hash _
      ((old++))
      printf '%s%s %s%s\n' "$color_old" "${hash::7}" "$line" "$sgr0"
    ;;
    (+*)
      read -ru 4 hash _
      ((new++))
      printf '%s%s %s%s\n' "$color_new" "${hash::7}" "$line" "$sgr0"
    ;;
  esac
done
