#!/usr/bin/env bash
# Lets you view the regular 'git diff' output in Vim and jump to the relevant
# file by pressing Enter

git diff --quiet && exit

tmpfile=$(mktemp)
vimfile=$(mktemp)
git diff "$@" > "$tmpfile"
cd "$(git rev-parse --show-toplevel)"

cat > "$vimfile" <<'EOF'
function! Jump()
    let selected_lineno = line('.')
    let linecount = 0

    if getline('.')[0:9] == 'diff --git'
        let diffline = selected_lineno
    else
        let diffline = search('^diff --git', 'bn')
    endif

    let plusline = diffline + 1
    while getline(plusline)[0:3] != '+++ '
        let plusline += 1
    endwhile
    let file = getline(plusline)[6:]

    if selected_lineno <= plusline
        let alfaline = plusline + 1
    elseif getline('.')[0:1] == '@@'
        let alfaline = selected_lineno
    else
        let alfaline = search('^@@', 'bn')
    endif

    for line in getline(alfaline + 1, selected_lineno)
        if line[0] != '-'
            let linecount += 1
        endif
    endfor

    let linenumber = matchstr(getline(alfaline), '+\zs\d\+') + linecount - 1
    execute 'split' '+call\ cursor('.linenumber.','.(col('.') - 1).')' file
endfunction
nnoremap <buffer> <Enter> :call Jump()<Enter>
setlocal filetype=diff
EOF

vim -S "$vimfile" "$tmpfile"

rm "$tmpfile" "$vimfile"
